walmart_project:
  outputs:
    dev:
      catalog: walmart
      host: dbc-ee86700c-451f.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ec48cebb926e806a
      schema: default
      threads: 1
      token: dapia4d32f56307fdff4023333##############
      type: databricks
  target: dev
